#!/usr/bin/python2

import os
import urllib2

if __name__ == '__main__':

    lib_dir = 'code/SecuML_web/base/static/lib/'
    js_dir = lib_dir + 'js/'
    css_dir = lib_dir + 'css/'

    os.makedirs(js_dir)
    os.makedirs(css_dir)

    js_url = ['https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js',
            'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js',
            'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js',
            'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.min.js',
            'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.0/js/bootstrap.min.js']

    css_url = ['http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
            'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css']

    for url in js_url:
        name = url.split('/')[-1]
        print 'Download', name
        f = urllib2.urlopen(url)
        with open(js_dir + name, 'w') as output:
            output.write(f.read())

    for url in css_url:
        name = url.split('/')[-1]
        print 'Download', name
        f = urllib2.urlopen(url)
        with open(css_dir + name, 'w') as output:
            output.write(f.read())
