#!/usr/bin/python3

import os
from urllib.parse import urlparse
import urllib.request

from SecuML.core.Tools import dir_tools
from SecuML.experiments.Tools import dir_exp_tools

def create_directory(directory):
    if not os.path.isdir(directory):
        os.makedirs(directory)

if __name__ == '__main__':

    lib_dir = 'SecuML/web/static/lib/'
    urls = dir_exp_tools.getWebUrls()
    for k in ['js', 'css']:
        directory = os.path.join(lib_dir, k)
        dir_tools.checkDirectoryExists(directory)
        for url in urls[k]:
            filename = os.path.basename(urlparse(url).path)
            print('Download', filename)
            req = urllib.request.Request(url)
            with urllib.request.urlopen(req) as response:
                with open(os.path.join(lib_dir, k, filename), 'wb') as output:
                    output.write(response.read())
