#!/usr/bin/python3

import glob
import os
import shutil
import urllib.request
import tarfile

def remove_directory(directory):
    if os.path.isdir(directory):
        shutil.rmtree(directory)

if __name__ == '__main__':
    url = 'http://www.aueb.gr/users/ion/data/lingspam_public.tar.gz'
    req = urllib.request.Request(url)
    with urllib.request.urlopen(req) as response:
        with open('data.tar', 'wb') as output:
            output.write(response.read())
    tar = tarfile.open('data.tar')
    tar.extractall(path = '.')
    tar.close()
    os.remove('data.tar')
    shutil.move('lingspam_public/bare', 'raw_mail')
    remove_directory('lingspam_public/')

    for filename in glob.glob('raw_mail/*/*.txt'):
        shutil.move(filename, 'raw_mail/')

    for directory in glob.glob('raw_mail/part*'):
        remove_directory(directory)
