#!/usr/bin/python2

## SecuML
## Copyright (C) 2016  ANSSI
##
## SecuML is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## SecuML is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License along
## with SecuML. If not, see <http://www.gnu.org/licenses/>.

import argparse
import matplotlib
matplotlib.use('Agg')

from SecuML.Clustering.Configuration import ClusteringConfFactory
from SecuML.Data.Dataset import Dataset
from SecuML.Data.Instances import Instances
from SecuML.Experiment.ClusteringExperiment import ClusteringExperiment
from SecuML.Tools import mysql_tools

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
            description = 'Clustering of the data for data exploration.')
    algos = ['Kmeans', 'GaussianMixture']
    subparsers = parser.add_subparsers(dest = 'algo')
    for algo in algos:
        algo_parser = subparsers.add_parser(algo)
        factory = ClusteringConfFactory.getFactory()
        factory.generateParser(algo, algo_parser)
    args = parser.parse_args()

    db, cursor = mysql_tools.getDbConnection()
    ## Check whether the dataset has been loaded before
    if not mysql_tools.databaseExists(cursor, args.project, args.dataset):
        load_dataset = Dataset(args.project, args.dataset,
                db, cursor)
        load_dataset.load()

    clustering_conf = factory.fromArgs(args.algo, args)
    experiment = ClusteringExperiment(args.project, args.dataset, db,
            cursor, clustering_conf)
    experiment.setFeaturesFilenames(args.features_files)
    experiment.initLabels(args.labels_file)
    experiment.export()

    instances = Instances()
    instances.initFromExperiment(experiment)
    if args.label != 'all':
        if args.label == 'malicious':
            selected_ids = instances.getMaliciousIds(true_labels = True)
        elif args.label == 'benign':
            selected_ids = instances.getBenignIds(true_labels = True)
        instances = instances.getInstancesFromIds(selected_ids)

    clustering = clustering_conf.algo(instances, experiment)
    clustering.run(instances)

    mysql_tools.closeDb(db, cursor)
