#!/usr/bin/python3

# SecuML
# Copyright (C) 2016-2019  ANSSI
#
# SecuML is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# SecuML is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with SecuML. If not, see <http://www.gnu.org/licenses/>.

import matplotlib.pyplot as plt
import sys

from secuml.core.tools.color import display_in_red
from secuml.core.tools.core_exceptions import SecuMLcoreException
from secuml.exp.projection import ProjectionExperiment
from secuml.exp.projection.conf import ProjectionConf
from secuml.exp.tools.exp_exceptions import SecuMLexpException


plt.switch_backend('Agg')


if __name__ == '__main__':
    try:
        parser = ProjectionConf.gen_parser()
        args = parser.parse_args()
        exp_conf = ProjectionConf.from_args(args)
        exp = ProjectionExperiment(exp_conf)
        exp.run()
        exp.close()
    except (SecuMLcoreException, SecuMLexpException) as e:
        sys.stderr.write(display_in_red(e) + '\n')
        exp.rollback_session()
        sys.exit(-1)
    except Exception as e:
        exp.rollback_session()
        raise(e)
