#!/usr/bin/python3

# SecuML
# Copyright (C) 2016-2018  ANSSI
#
# SecuML is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# SecuML is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with SecuML. If not, see <http://www.gnu.org/licenses/>.

import matplotlib
matplotlib.use('Agg')
import sys

from SecuML.core.tools import colors_tools

from SecuML.exp.classification.ClassificationConf \
        import ClassificationConf
from SecuML.exp.classification.ClassificationExperiment \
        import ClassificationExperiment

from SecuML.core.tools.core_exceptions import SecuMLcoreException
from SecuML.exp.tools.exp_exceptions import SecuMLexpException

if __name__ == '__main__':
    try:
        parser = ClassificationConf.generateParser()
        args = parser.parse_args()
        exp_conf = ClassificationConf.fromArgs(args)
        exp = ClassificationExperiment(exp_conf)
        exp.run()
        exp.close()
    except (SecuMLcoreException, SecuMLexpException) as e:
        sys.stderr.write(colors_tools.display_in_red(e) + '\n')
        exp.rollbackSession()
        sys.exit(-1)
    except Exception as e:
        exp.rollbackSession()
        raise(e)
