#!/usr/bin/python2

## SecuML
## Copyright (C) 2016-2017  ANSSI
##
## SecuML is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## SecuML is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License along
## with SecuML. If not, see <http://www.gnu.org/licenses/>.

import matplotlib
matplotlib.use('Agg')
import sys

from SecuML.ActiveLearning.Configuration.ActiveLearningConfiguration import InvalidInputArguments
from SecuML.ActiveLearning.ActiveLearning import ActiveLearning
from SecuML.Experiment.ActiveLearningExperiment import ActiveLearningExperiment

if __name__ == '__main__':

    parser = ActiveLearningExperiment.generateParser()
    args = parser.parse_args()

    experiment = ActiveLearningExperiment(args.project, args.dataset, None)
    try:
        experiment.setExperimentFromArgs(args)
    except InvalidInputArguments as e:
        print e
        experiment.closeSession()
        sys.exit()

    iterations = ActiveLearning(experiment)
    if not args.auto:
        from CeleryApp.app import secumlworker
        from CeleryApp.activeLearningTasks import IterationTask
        options = {}
        # bind iterations object to IterationTask class
        iterations.runNextIteration()
        IterationTask.iteration_object = iterations
        # Start worker
        secumlworker.enable_config_fromcmdline = False
        secumlworker.run(**options)
    else:
        iterations.runIterations()

    experiment.closeSession()
